# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Events"
url = "/events"
weight = 2

[[main]]
name = "Projects"
url = "/projects"
weight = 3

[[main]]
name = "Publications"
url = "/publications"
weight = 4

[[main]]
name = "Units"
url = "/units"
weight = 5

[[main]]
name = "Labs"
url = "/labs"
weight = 6

# footer menu left
[[footer_left]]
name = "About Us"
url = "#"

[[footer_left]]
name = "Quick Start"
url = "#"

[[footer_left]]
name = "Projects"
url = "/projects"


# footer menu middle
[[footer_middle]]
name = "Projects"
url = "/projects"

[[footer_middle]]
name = "Platform"
url = "#"

[[footer_middle]]
name = "Features"
url = "#"

# footer menu right
[[footer_right]]
name = "Privacy Policy"
url = "/privacy-policy"

[[footer_right]]
name = "Terms & Conditions"
url = "/terms-conditions"

[[footer_right]]
name = "Units"
url = "/units"